[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "send_mail_simplified"
version = "0.2.0"
description = "Small SMTP email sender utility"
authors = [ { name = "Breion, Yuri" } ]
requires-python = ">=3.8"
